// Fetch Restaraunt
export const FETCH_RESTARAUNTS_INIT = 'FETCH_RESTARAUNTS_INIT';
export const FETCH_RESTARAUNTS_SUCCESS = 'FETCH_RESTARAUNTS_SUCCESS';
export const FETCH_RESTARAUNTS_FAIL = 'FETCH_RESTARAUNTS_FAIL';

export const UPDATE_RESTARAUNT_INIT = 'UPDATE_RESTARAUNT_INIT';
export const UPDATE_RESTARAUNT_SUCCESS = 'UPDATE_RESTARAUNT_INIT';
export const UPDATE_RESTARAUNT_FAIL = 'UPDATE_RESTARAUNT_INIT';

// Fetch Restaraunt Details
export const FETCH_RESTARAUNT_DETAIL_INIT = 'FETCH_RESTARAUNT_DETAIL_INIT';
export const FETCH_RESTARAUNT_DETAIL_SUCCESS = 'FETCH_RESTARAUNT_DETAIL_SUCCESS';
export const FETCH_RESTARAUNT_DETAIL_FAIL = 'FETCH_RESTARAUNT_DETAIL_FAIL';